version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-dev-onprem-dwh
    ports:
      - "${PORT:-1433}:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      MSSQL_AGENT_ENABLED: "true"
    volumes:
      - mssql-data:/var/opt/mssql/data

volumes:
  mssql-data: